spring:
  application:
    name: timesheet management

  datasource:
    url: jdbc:mysql://localhost:3306/timesheet_management
    username: root
    password: root@2479
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
